### PR TITLE
Master

### PR DESCRIPTION
**Pull request by the-saif-ahmad**
Implemented save feature

### CODE REVIEW

**Comment by the-saif-ahmad** [comment]
Still having frequent errors when attempting to load the file

**Comment by ProgrammerDan** [comment]
Wow! Bravo for tackling this, I've been pretty far removed from it mentally of late. 

What kind of errors? Pastebin the stacktrace.

**Comment by the-saif-ahmad** [comment]
http://pastebin.com/pAjHQKqB

**Comment by ProgrammerDan** [comment]
Hmm, this is a hard one. Basically, during load there are some null words, so the "hashing" function I have is returning null here: https://github.com/ProgrammerDan/learning-chatbot/pull/2/files#diff-bfa23ce7f4ee1ce2a14620685804695aR863

Guessing a bit, but I'd expect that for some reason either the serialization isn't saving the word data, or on load it's attempting to stuff the HashMap before it fills the values of the ChatWord. You might need to write a custom serialization routine - [see the docs here](https://docs.oracle.com/javase/8/docs/platform/serialization/spec/serialTOC.html) - or it may be more efficient to simply remap the data to an intermediate representation that's a bit more "flat" so to speak.

**Comment by ProgrammerDan** [comment]
Any luck on fixing this?

**Comment by ProgrammerDan** [comment]
Check out my solution in the bfs branch.

**Pull request closed without merging**
